-- Seed data for debts table
-- Generated from MinerDataCenterSites spreadsheet, Debt worksheet
-- 40 debt instruments across 15 companies

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'APLD',
  '2.75% Convertible Senior Notes due 2030',
  'Convertible Note',
  'Applied Digital Corp',
  450,
  450,
  '2030-06-01',
  0.0275,
  12.375,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  9.75,
  'Outstanding',
  'HIGH',
  'https://ir.applieddigital.com/news-events/press-releases/detail/111/',
  '2025-06-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'APLD',
  '9.25% Senior Secured Notes due 2030 (APLD ComputeCo)',
  'Sr Secured Note',
  'APLD ComputeCo LLC',
  2350,
  2350,
  '2030-12-01',
  0.0925,
  217.375,
  TRUE,
  'First-priority liens on all assets of APLD ComputeCo, equity interests, project accounts at Ellendale ND campus',
  'Project',
  'Ellendale ND (Polaris Forge 1)',
  FALSE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://ir.applieddigital.com/news-events/press-releases/detail/136/',
  '2025-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'APLD',
  '0.25% Equipment Financing (Macquarie)',
  'Equipment Fin',
  'Applied Digital Corp',
  150,
  150,
  '2026-05-01',
  0.0025,
  0.375,
  TRUE,
  'Equipment collateral at Ellendale facility',
  'Project',
  'Ellendale ND',
  FALSE,
  NULL,
  'Outstanding (may be partially repaid)',
  'MEDIUM',
  'https://ir.applieddigital.com/news-events/press-releases/detail/113/',
  '2024-06-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'WULF',
  '2.75% Convertible Senior Notes due 2030',
  'Convertible Note',
  'TeraWulf Inc',
  500,
  500,
  '2030-02-01',
  0.0275,
  13.75,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  8.48,
  'Outstanding',
  'HIGH',
  'https://investors.terawulf.com/news-events/press-releases/detail/93/',
  '2025-02-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'WULF',
  '1.00% Convertible Senior Notes due 2031',
  'Convertible Note',
  'TeraWulf Inc',
  850,
  850,
  '2031-08-01',
  0.01,
  8.5,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  12.43,
  'Outstanding',
  'HIGH',
  'https://investors.terawulf.com/news-events/press-releases/detail/116/',
  '2025-08-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'WULF',
  '0.00% Convertible Senior Notes due 2032',
  'Convertible Note',
  'TeraWulf Inc',
  1025,
  1025,
  '2032-10-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  19.94,
  'Outstanding',
  'HIGH',
  'https://investors.terawulf.com/news-events/press-releases/detail/123/',
  '2025-10-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'WULF',
  '7.75% Senior Secured Notes due 2030 (WULF Compute)',
  'Sr Secured Note',
  'WULF Compute LLC',
  3200,
  3200,
  '2030-10-01',
  0.0775,
  248,
  TRUE,
  'First-priority liens on Lake Mariner assets, equity pledges, Fluidstack lockbox, Google warrants',
  'Project',
  'Lake Mariner NY',
  FALSE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://investors.terawulf.com/news-events/press-releases/detail/119/',
  '2025-10-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CIFR',
  '0.00% Convertible Senior Notes due 2031',
  'Convertible Note',
  'Cipher Mining Inc',
  1300,
  1300,
  '2031-10-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  16.03,
  'Outstanding',
  'HIGH',
  'https://investors.ciphermining.com/news-releases/',
  '2025-10-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CIFR',
  '7.125% Senior Secured Notes due 2030 (Cipher Compute)',
  'Sr Secured Note',
  'Cipher Compute LLC',
  1733,
  1733,
  '2030-11-01',
  0.0712,
  123.4762,
  TRUE,
  'First-priority liens on all assets of Cipher Compute LLC (Barber Lake Facility, CO)',
  'Project',
  'Barber Lake TX',
  FALSE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://www.globenewswire.com/news-release/2025/11/06/3182126/',
  '2025-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CIFR',
  '6.125% Senior Secured Notes due 2031 (Black Pearl)',
  'Sr Secured Note',
  'Black Pearl Compute LLC',
  2000,
  2000,
  '2031-02-01',
  0.0612,
  122.5,
  TRUE,
  'First-priority liens on all assets of Black Pearl Compute LLC (Black Pearl Facility, Wink TX)',
  'Project',
  'Black Pearl TX',
  FALSE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://www.globenewswire.com/news-release/2026/02/04/3232548/',
  '2026-02-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'RIOT',
  '0.75% Convertible Senior Notes due 2030',
  'Convertible Note',
  'Riot Platforms Inc',
  594.4,
  594.4,
  '2030-01-01',
  0.0075,
  4.458,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  14.86,
  'Outstanding',
  'HIGH',
  'https://www.riotplatforms.com/riot-announces-closing-of-594-4-million-convertible-senior-notes-offering/',
  '2025-01-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'IREN',
  '3.50% Convertible Senior Notes due 2029 (partially repurchased)',
  'Convertible Note',
  'IREN Limited',
  233.4,
  550,
  '2029-12-01',
  0.035,
  8.169,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  13.64,
  'Partial Repurchase ($316.6M bought back Dec-2025)',
  'HIGH',
  'https://irisenergy.gcs-web.com/news-releases/news-release-details/iren-closes-upsized-550-million-convertible-notes-offering',
  '2025-12-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'IREN',
  '3.25% Convertible Senior Notes due 2030 (partially repurchased)',
  'Convertible Note',
  'IREN Limited',
  212.3,
  440,
  '2030-12-01',
  0.0325,
  6.8998,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  16.81,
  'Partial Repurchase ($227.7M bought back Dec-2025)',
  'HIGH',
  'https://www.globenewswire.com/news-release/2024/12/06/2993278/',
  '2025-12-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'IREN',
  '0.00% Convertible Senior Notes due 2031',
  'Convertible Note',
  'IREN Limited',
  1000,
  1000,
  '2031-10-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://irisenergy.gcs-web.com/news-releases/news-release-details/iren-closes-10-billion-convertible-notes-offering',
  '2025-10-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'IREN',
  '0.25% Convertible Senior Notes due 2032',
  'Convertible Note',
  'IREN Limited',
  1150,
  1150,
  '2032-06-01',
  0.0025,
  2.875,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://www.globenewswire.com/news-release/2025/12/08/3201998/',
  '2025-12-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'IREN',
  '1.00% Convertible Senior Notes due 2033',
  'Convertible Note',
  'IREN Limited',
  1150,
  1150,
  '2033-06-01',
  0.01,
  11.5,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://www.globenewswire.com/news-release/2025/12/08/3201998/',
  '2025-12-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'HUT',
  '8.00% Convertible Note (Coatue)',
  'Convertible Note',
  'Hut 8 Corp',
  150,
  150,
  '2029-06-01',
  0.08,
  12,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  16.4,
  'Outstanding',
  'HIGH',
  'https://www.sec.gov/Archives/edgar/data/1964789/000155837024009418/hut-20240621x8k.htm',
  '2024-06-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'GLXY',
  '2.50% Exchangeable Senior Notes due 2029',
  'Exchangeable Note',
  'Galaxy Digital Holdings',
  402.5,
  402.5,
  '2029-12-01',
  0.025,
  10.0625,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  23.81,
  'Outstanding',
  'HIGH',
  'https://www.nasdaq.com/articles/galaxy-digital-closes-4025m-exchangeable-notes-offering',
  '2024-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'GLXY',
  'SOFR+475bps Term Loan (Galaxy Helios I)',
  'Term Loan',
  'Galaxy Helios I LLC',
  1400,
  1400,
  '2028-08-01',
  0.091,
  127.4,
  TRUE,
  'All assets of Galaxy Helios I, equity interests; Deutsche Bank agent',
  'Project',
  'Helios Campus TX',
  FALSE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://www.sec.gov/Archives/edgar/data/1859392/000185939225000040/',
  '2025-08-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'SLNH',
  'Project Dorothy 2 Finance (Spring Lane Capital)',
  'Project Fin',
  'SCI Dorothy 2 LLC',
  30,
  30,
  NULL,
  0.1,
  3,
  TRUE,
  'Project Dorothy 2 facility assets and cash flows (48 MW)',
  'Project',
  'Dorothy 2 TX',
  FALSE,
  NULL,
  'Outstanding',
  'MEDIUM',
  'https://www.solunacomputing.com/news/soluna-closes-30m-funding-from-spring-lane-capital-for-project-dorothy-2/',
  '2024-07-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'SLNH',
  'Galaxy Digital Term Loan',
  'Term Loan',
  'Soluna subsidiary',
  5,
  5,
  '2030-03-01',
  0.1,
  0.5,
  TRUE,
  'Project-level cash flows (limited recourse)',
  'Project',
  NULL,
  FALSE,
  NULL,
  'Outstanding',
  'MEDIUM',
  'https://www.businesswire.com/news/home/20250318203334/en/',
  '2025-03-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CLSK',
  '0.00% Convertible Senior Notes due 2030',
  'Convertible Note',
  'CleanSpark Inc',
  650,
  650,
  '2030-12-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  14.8,
  'Outstanding',
  'HIGH',
  'https://www.prnewswire.com/news-releases/cleanspark-inc-announces-closing-of-offering-of-650-million-zero-coupon-convertible-notes-302334225.html',
  '2024-12-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CLSK',
  '0.00% Convertible Senior Notes due 2032',
  'Convertible Note',
  'CleanSpark Inc',
  1150,
  1150,
  '2032-02-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  19.16,
  'Outstanding',
  'HIGH',
  'https://www.prnewswire.com/news-releases/cleanspark-inc-announces-closing-of-upsized-1-15-billion-zero-coupon-convertible-notes-offering-302615019.html',
  '2025-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CORZ',
  'Exit Credit Facility (post-Ch11, partially repaid)',
  'Term Loan',
  'Core Scientific Inc',
  19,
  80,
  '2027-01-01',
  0.09,
  1.71,
  TRUE,
  'First-lien on corporate assets',
  'Corporate',
  NULL,
  FALSE,
  NULL,
  'Partially Repaid ($61M repaid Aug-2024)',
  'MEDIUM',
  'https://investors.corescientific.com/sec-filings/all-sec-filings/content/0001193125-24-013078/',
  '2024-01-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CORZ',
  '3.00% Convertible Senior Notes due 2029',
  'Convertible Note',
  'Core Scientific Inc',
  400,
  400,
  '2029-09-01',
  0.03,
  12,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  11,
  'Outstanding',
  'HIGH',
  'https://investors.corescientific.com/news-events/press-releases/detail/88/',
  '2024-08-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'CORZ',
  '0.00% Convertible Senior Notes due 2031',
  'Convertible Note',
  'Core Scientific Inc',
  625,
  625,
  '2031-06-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  22.49,
  'Outstanding',
  'HIGH',
  'https://investors.corescientific.com/news-events/press-releases/detail/102/',
  '2024-12-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'BTDR',
  '5.25% Convertible Senior Notes due 2029',
  'Convertible Note',
  'Bitdeer Technologies Group',
  360,
  360,
  '2029-12-01',
  0.0525,
  18.9,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  15.95,
  'Outstanding',
  'HIGH',
  'https://ir.bitdeer.com/',
  '2024-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'BTDR',
  '4.875% Convertible Senior Notes due 2031',
  'Convertible Note',
  'Bitdeer Technologies Group',
  330,
  330,
  '2031-06-01',
  0.0488,
  16.0875,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  14.49,
  'Outstanding',
  'HIGH',
  'https://ir.bitdeer.com/',
  '2025-06-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'BTDR',
  '4.00% Convertible Senior Notes due 2031',
  'Convertible Note',
  'Bitdeer Technologies Group',
  400,
  400,
  '2031-11-01',
  0.04,
  16,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  17.77,
  'Outstanding',
  'HIGH',
  'https://ir.bitdeer.com/',
  '2025-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'BITF',
  '1.375% Convertible Senior Notes due 2031',
  'Convertible Note',
  'Bitfarms Ltd',
  588,
  588,
  '2031-01-01',
  0.0138,
  8.085,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  6.86,
  'Outstanding',
  'HIGH',
  'https://investor.bitfarms.com/',
  '2025-10-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'BITF',
  'Stronghold Digital Assumed Debt',
  'Assumed Debt',
  'Stronghold Digital Mining',
  50,
  50,
  NULL,
  0.1,
  5,
  TRUE,
  'Stronghold facility assets (Scrubgrass, Panther Creek)',
  'Project',
  'Panther Creek / Scrubgrass PA',
  FALSE,
  NULL,
  'Outstanding (terms undisclosed)',
  'LOW',
  'https://investor.bitfarms.com/',
  '2025-03-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'HIVE',
  '8.00% Convertible Debentures (US Global)',
  'Convertible Note',
  'HIVE Digital Technologies',
  15,
  15,
  '2026-01-01',
  0.08,
  1.2,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  NULL,
  'At/Near Maturity (Jan-2026)',
  'MEDIUM',
  'https://www.hivedigitaltechnologies.com/news/',
  '2021-01-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'HIVE',
  'Atlantic Term Loans (2 facilities, CAD)',
  'Term Loan',
  'Atlantic Datacentres',
  5,
  5,
  NULL,
  0.0333,
  0.1665,
  TRUE,
  'Atlantic Datacentres assets',
  'Project',
  'Atlantic Canada',
  FALSE,
  NULL,
  'Outstanding (~C$6.8M)',
  'MEDIUM',
  'HIVE 6-K Jun 30, 2024',
  '2024-06-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'FUFU',
  'Equipment Financing (various)',
  'Equipment Fin',
  'BitFuFu Inc',
  141,
  NULL,
  NULL,
  0.1,
  14.1,
  TRUE,
  'Mining equipment',
  'Asset',
  'Various',
  FALSE,
  NULL,
  'Outstanding (rate undisclosed)',
  'LOW',
  'BitFuFu balance sheet Sep-2025',
  '2025-09-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'FUFU',
  'Antpool Credit Facility ($100M, undrawn)',
  'Revolver',
  'BitFuFu Inc',
  0,
  100,
  '2026-11-01',
  0.065,
  0,
  TRUE,
  'Bitcoin (70% LTV)',
  'Corporate',
  NULL,
  FALSE,
  NULL,
  'Undrawn ($0 of $100M)',
  'HIGH',
  'BitFuFu press release Nov-2024',
  '2024-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'MARA',
  '1.00% Convertible Senior Notes due 2026 (partially repurchased)',
  'Convertible Note',
  'MARA Holdings Inc',
  468,
  750,
  '2026-01-01',
  0.01,
  4.68,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  NULL,
  'Partial Repurchase (~$282M bought back)',
  'MEDIUM',
  'https://ir.mara.com/',
  '2025-07-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'MARA',
  '2.125% Convertible Senior Notes due 2031',
  'Convertible Note',
  'MARA Holdings Inc',
  300,
  300,
  '2031-09-01',
  0.0213,
  6.375,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  18.89,
  'Outstanding',
  'HIGH',
  'https://www.globenewswire.com/news-release/2024/08/14/2930552/',
  '2024-08-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'MARA',
  '0.00% Convertible Senior Notes due 2030',
  'Convertible Note',
  'MARA Holdings Inc',
  1000,
  1000,
  '2030-03-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  25.91,
  'Outstanding',
  'HIGH',
  'https://ir.mara.com/news-events/press-releases/detail/1379/',
  '2024-11-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'MARA',
  '0.00% Convertible Senior Notes due 2031',
  'Convertible Note',
  'MARA Holdings Inc',
  850,
  850,
  '2031-06-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  34.58,
  'Outstanding',
  'HIGH',
  'https://ir.mara.com/news-events/press-releases/detail/1384/',
  '2024-12-01',
  NOW(),
  NOW()
);

INSERT INTO "debts" (id, ticker, instrument, debt_type, issuer, principal_m, original_m, maturity, coupon_pct, annual_interest_m, secured, collateral, level, linked_site, convertible, conversion_price, status, confidence, source, source_date, created_at, updated_at) VALUES (
  gen_random_uuid(),
  'MARA',
  '0.00% Convertible Senior Notes due 2032',
  'Convertible Note',
  'MARA Holdings Inc',
  950,
  950,
  '2032-08-01',
  0,
  0,
  FALSE,
  NULL,
  'Corporate',
  NULL,
  TRUE,
  NULL,
  'Outstanding',
  'HIGH',
  'https://ir.mara.com/news-events/press-releases/detail/1404/',
  '2025-07-01',
  NOW(),
  NOW()
);
